#!/usr/bin/env bash

set -euo pipefail

if [ "$#" -eq 0 ]; then
  echo "Please specify the command-line options to pass to 'fourmolu'" >&2
  exit 1
fi

git_root=$(git rev-parse --show-toplevel)
fourmolu=$(nix-build "${git_root}/nix/pkgs.nix" --attr haskellPackages.fourmolu  --no-out-link)
standard_options=(\
  --ghc-opt -XTypeApplications \
  --ghc-opt -XBangPatterns \
  --ghc-opt -XTypeOperators \
  --ghc-opt -XPatternSynonyms \
)

"${fourmolu}/bin/fourmolu" "${standard_options[@]}" "$@"
